### ISSUE TITLE
在线等一份大佬部署教程

### ISSUE THREAD

**Issue by tlerbao** [NotoChen/Jetbrains-Help#5]
如题，

**Comment by justmd5** [comment]
还要啥部署教程，Dockerfile都给了，自己编一下不就能用了么

**Comment by tlerbao** [comment]
> 还要啥部署教程，Dockerfile都给了，自己编一下不就能用了么

你是无法想象我有多菜，这不是我的领域哈哈

**Comment by NotoChen** [comment]
等我晚点再更新一下readme把完成教程写上

**Comment by tlerbao** [comment]
> 等我晚点再更新一下readme把完成教程写上

牛逼，感谢大佬

**Comment by Carlos920** [comment]
#### docker-compose.yml
```yaml
services:
  jetbrains-help:
    build: .
    image: jetbrains-help:latest
    container_name: Jetbrains-Help
    ports:
      - 10768:10768
    volumes:
      - ./external:/external
```


```bash
docker compose build && docker compose up -d
```
